image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "@min-jus-gba-informatica-global:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm install
    - npm publish
  only:
    - tags
